### ISSUE TITLE
Random crashes with 1.4.0.2

### ISSUE THREAD

**Issue by coldino** [DeadlyCrush/DeadlyTrade#22]
I've used 1.4.0.0 for a while with no problem, but the latest version randomly crashes after some time - sometimes just a few minutes. Not able to keep it running for more than half an hour.

Maybe related: this version throws a warning on startup: 
![image](https://user-images.githubusercontent.com/28345893/76682722-5a537300-65f6-11ea-961f-c542c292aadf.png)

I have very few hotkeys enabled, and they are the sames ones as the previous version. I have no other hotkey software running.

**Comment by DeadlyCrush** [comment]
Thank you for your report.

=======================
1.4.0.3 DeadlyTrade Released.

○ CONFIG File is changed.
- Sorry, CONFIG File is changed for BUG Fix.

○ BUG FIX
- Fixed Labyrinth Overlay Zoomin, Zoomout, Close Button Action
- Fixed Moving stash tab by CTRL+MouseWheel
- Fixed Trade Notification Pop-up
- Fixed Korean Trade Message Parsing
. Korean trade whisper changed that cause trade message parsing bug.
. Korean trade whisper's a few default words was changed. ex) 을(를) to (을)를
- Fixed Cache File Cleaner : ShaderCacheD3D11 & ShaderCacheD3D11_GI
- Fixed Save Configuration in Settings.

**Comment by coldino** [comment]
Tried this last night with 1.4.0.4 and it still crashed after some time.

There's no error reported and I can't see a log file. Maybe I'll fire up VS later and see if I can catch the cause.
